
DayChangeCheckRateInSeconds: 20
DayCheckWorldToUse: world

GrowthCheckRateInMinutes: 1

WorldsAffectedByPrecipitation:
  - world

TemperatureCheckRateInSeconds: 20
PrecipitationCheckRateInSeconds: 300

MaxTemperatureBeforeHeatDamage: 25
MinTemperatureBeforeColdDamage: 0
DamageRate: 0.1

FireResistanceIgnoresHeatDamage: true
# Currently configured to reduce by 25% per level. If IV or higher, damage
# is reduced to zero.
FireProtectionReducesHeatDamage: true

OutdoorBlockChecks:
  - 1,1,0
  - -1,1,0
  - 0,1,1
  - 0,1,-1
  - 0,2,0
  
BlockTemperatureModifierCheckRadius: 1

HungerDamageRestoredFromWaterBottle: 4
  
BlockTemperatureModifier:
  LAVA: 4
  STATIONARY_LAVA: 4
  SNOW: -1
  SNOW_BLOCK: -1
  FROSTED_ICE: -1
  ICE: -1
  PACKED_ICE: -1
  
HeldItemTemperatureModifier:
  TORCH: 5
  LAVA_BUCKET: 15
  SNOW_BALL: -4

ArmorTemperatureModifier:
  LEATHER_BOOTS:
    Cold: 4
    Heat: -4
  LEATHER_LEGGINGS:
    Cold: 4
    Heat: -4
  LEATHER_CHESTPLATE:
    Cold: 4
    Heat: -4
  LEATHER_HELMET:
    Cold: 4
    Heat: -4
  GOLD_BOOTS:
    Cold: 4
    Heat: -4
  GOLD_LEGGINGS:
    Cold: 4
    Heat: -4
  GOLD_CHESTPLATE:
    Cold: 4
    Heat: -4
  GOLD_HELMET:
    Cold: 4
    Heat: -4
  IRON_BOOTS:
    Cold: 4
    Heat: -4
  IRON_LEGGINGS:
    Cold: 4
    Heat: -4
  IRON_CHESTPLATE:
    Cold: 4
    Heat: -4
  IRON_HELMET:
    Cold: 4
    Heat: -4
  DIAMOND_BOOTS:
    Cold: 0
    Heat: 0
  DIAMOND_LEGGINGS:
    Cold: 0
    Heat: 0
  DIAMOND_CHESTPLATE:
    Cold: 0
    Heat: 0
  DIAMOND_HELMET:
    Cold: 0
    Heat: 0

# Used if Seasons is disabled but other season-bound components are enabled
Default:
  DayLength: 12000
  NightLength: 12000
  Config: configurations/environment/default/

# Setting the Day and Night cycle

# Time is lengthened by constantly pausing, then resuming, the daylight cycle.
# The config options you have will allow you to adjust how long to pause and
# how much time is between pauses.
# 
# TicksBetweenPauses: Number of ticks time is normal before pausing.
# 
# TicksPerPause: Number of ticks time is paused before resuming.
#
# By default, the time length for a day or night cycle is 12000 ticks (10m).
# The way to calculate what the new length for your cycle is given by:
#
# New Length = (TicksBetweenPauses + TicksPerPause)/TicksBetweenPauses * 12000
# 
# A simplier way to look at this is: 
#
# Time Multiplier = (TicksBetweenPauses + TicksPerPause)/TicksBetweenPauses
#
# If you want to double the time, set both config options to the same value:
#    
# Time Multiplier = (X + X)/X = 2X/X = 2
#
# If you want to increase the time by 50%, set TicksPerPause to half of what
# you set TicksBetweenPauses.
#
# Time Multiplier = (2X + X)/2X = 3X/2X = 1.5
#
#
# Notably, this means you can have multiple ways of setting the values to 
# achieve the same daylight length. For example, setting both values to 1
# and setting both values to 10 will both double the time length. The difference
# becomes how often the transitions occur. If both are set to 1, this means a
# transition occurs every tick. If they're both set to 10, the transition occurs
# every 10 ticks. Using low values may result in poor server performance. Using
# high values may result in rather noticable stops in the time cycle when 
# looking at the sun/moon.
Seasons:
  Spring:
    Duration: 1
    # Set to 15m
    DayCycle:
      TicksBetweenPauses: 20
      TicksPerPause: 10
    # Set to 15m
    NightCycle:
      TicksBetweenPauses: 20
      TicksPerPause: 10
    Config: configurations/environment/Spring
  Summer:
    Duration: 1
    # Set to 20m
    DayCycle:
      TicksBetweenPauses: 20
      TicksPerPause: 20
    # Night cycle not set, defaults to 10m
    Config: configurations/environment/Summer
